version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: flexusaurs/nodeswarm:v4
    restart: unless-stopped
    environment:
     - NODE_ENV=dev
    ports:
      - "8080:8080"
    
    deploy:
      replicas: 4
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 1s

  proxy:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    image: flexusaurs/nginx-proxy:v1
    ports:
      - 80:80
    depends_on:
      - nodejs
    deploy:
      placement:
        constraints: [node.role == manager]